### ISSUE TITLE
Check migrate log getting error

### ISSUE THREAD

**Issue by skanel** [bigcapitalhq/bigcapital#264]
`docker logs -f 2e8942de6337`

`wait-for-it.sh: waiting 15 seconds for mysql:3306
wait-for-it.sh: timeout occurred after waiting 15 seconds for mysql:3306
Error: connect ECONNREFUSED 172.19.0.3:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
    --------------------
    at Protocol._enqueue (/app/packages/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/app/packages/server/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/app/packages/server/node_modules/mysql/lib/Connection.js:116:18)
    at /app/packages/server/node_modules/knex/lib/dialects/mysql/index.js:66:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/app/packages/server/node_modules/knex/lib/dialects/mysql/index.js:61:12)
    at create (/app/packages/server/node_modules/knex/lib/client.js:247:39)`

**Comment by abouolia** [comment]
Sounds from what I see, the database container has not started, the migration container waited for it but the timeout triggered.

**Comment by skanel** [comment]
now , no error log found, and site up running , but I cannot register.

**Comment by abouolia** [comment]
- Did you configure your .env at least you have to copy them from .env.example.
- Did you verify all containers are running like this one, https://docs.bigcapital.ly/deployment/docker#verify-the-installation
- Did you verify the migration ran successfully, you can verify by `docker ps -a | grep bigcapital-database_migration` and show the logs of that container by `docker logs -f CONTAINER_ID`.

Let us answer these questions first.

**Comment by skanel** [comment]
I did not change any thing even the .env file , I have kept all as it source.

![image](https://github.com/bigcapitalhq/bigcapital/assets/8022270/ac7c0640-68ef-4b4d-be86-76d2b6a8af78)
