### ISSUE TITLE
[BUG] Journal Sheet - Cannot read properties of undefined (reading 'columns')

### ISSUE THREAD

**Issue by xprnio** [bigcapitalhq/bigcapital#319]
For some reason, the Journal Sheet page doesn't seem to show up properly.
There are no failed API responses; the only error is the one below leading me to believe this is solely an issue on the webapp side.

```
TypeError: Cannot read properties of undefined (reading 'columns')
    at ue (dynamicColumns.ts:133:31)
    at ce (JournalTable.tsx:31:19)
    at qa (react-dom.production.min.js:167:137)
    at qs (react-dom.production.min.js:290:337)
    at vu (react-dom.production.min.js:280:389)
    at Ou (react-dom.production.min.js:280:320)
    at hu (react-dom.production.min.js:280:180)
    at uu (react-dom.production.min.js:273:245)
    at Ho (react-dom.production.min.js:127:105)
    at e.lu [as batchNotifyFn] (react-dom.production.min.js:274:82)
```

**Comment by xprnio** [comment]
I'll have a look at this in an hour or two and try to see if I can figure it out myself. @abouolia I think you can assign it to me (I tagged you because I assume you're somebody on the leading side of the project).

**Comment by abouolia** [comment]
@xprnio It works from my side, could you please open up the `Inspect` on your browser and give me the response of journal sheet.

**Comment by xprnio** [comment]
`GET /api/financial_statements/journal?from_date=2024-01-01&to_date=2024-01-20&basis=accrual&display_columns_by=&display_columns_type=total&none_zero=false&none_transactions=false&only_active=false`

```json
{
    "data": [
        {
            "date": "2024-01-20T00:00:00.000Z",
            "reference_type": "Expense",
            "reference_id": 1001,
            "reference_type_formatted": "Expense",
            "entries": [
                {
                    "entry_id": 1015,
                    "index": 1,
                    "note": null,
                    "account_name": "Arveldusarve (Swedbank)",
                    "account_code": "10121",
                    "transaction_number": null,
                    "currency_code": "EUR",
                    "formatted_credit": "19.45",
                    "formatted_debit": "",
                    "credit": 19.45,
                    "debit": 0,
                    "created_at": "2024-01-20T17:26:55.000Z"
                },
                {
                    "entry_id": 1016,
                    "index": 2,
                    "note": "Internet",
                    "account_name": "Andmeside",
                    "account_code": "40623",
                    "transaction_number": null,
                    "currency_code": "EUR",
                    "formatted_credit": "",
                    "formatted_debit": "19.45",
                    "credit": 0,
                    "debit": 19.45,
                    "created_at": "2024-01-20T17:26:55.000Z"
                }
            ],
            "currency_code": "EUR",
            "credit": 19.45,
            "debit": 19.45,
            "formatted_credit": "€19.45",
            "formatted_debit": "€19.45"
        },
        {
            "date": "2024-01-20T00:00:00.000Z",
            "reference_type": "Expense",
            "reference_id": 1005,
            "reference_type_formatted": "Expense",
            "entries": [
                {
                    "entry_id": 1031,
                    "index": 1,
                    "note": null,
                    "account_name": "Arveldusarve (Swedbank)",
                    "account_code": "10121",
                    "transaction_number": null,
                    "currency_code": "EUR",
                    "formatted_credit": "1.99",
                    "formatted_debit": "",
                    "credit": 1.99,
                    "debit": 0,
                    "created_at": "2024-01-20T17:42:04.000Z"
                },
                {
                    "entry_id": 1032,
                    "index": 2,
                    "note": "Kaarditoimingu teenustasu",
                    "account_name": "Panga teenustasud",
                    "account_code": "40687",
                    "transaction_number": null,
                    "currency_code": "EUR",
                    "formatted_credit": "",
                    "formatted_debit": "1.99",
                    "credit": 0,
                    "debit": 1.99,
                    "created_at": "2024-01-20T17:42:04.000Z"
                }
            ],
            "currency_code": "EUR",
            "credit": 1.99,
            "debit": 1.99,
            "formatted_credit": "€1.99",
            "formatted_debit": "€1.99"
        }
    ],
    "query": {
        "from_date": "2024-01-01",
        "to_date": "2024-01-20",
        "from_range": null,
        "to_range": null,
        "accounts_ids": [
            null
        ],
        "number_format": {
            "no_cents": false,
            "divide_on_1000": false
        }
    },
    "meta": {
        "is_cost_compute_running": false,
        "organization_name": false,
        "base_currency": false
    }
}
```

**Comment by abouolia** [comment]
@xprnio Sounds the server or webapp container (one of them) is not up-to-date, that response was exist in the old version, that's why the error popped up because the webapp expected a different interface. here's how to upgrade https://docs.bigcapital.ly/deployment/docker#upgrading.

**Comment by xprnio** [comment]
@abouolia That seemed to help, although I already had the latest git state and the images pulled oddly fast. Thank you for the quick response
