### ISSUE TITLE
Error: New Relic requires that you name this application! 

### ISSUE THREAD

**Issue by calm108** [bigcapitalhq/bigcapital#487]
Just deployed bigcapital via docker.  Keep seeing this in the server logs and  the app keeps crashing:

New Relic for Node.js was unable to bootstrap itself due to an error:
2024-06-06 15:03:34 Error: New Relic requires that you name this application!
2024-06-06 15:03:34 Set app_name in your newrelic.js or newrelic.cjs file or set environment variable
2024-06-06 15:03:34 NEW_RELIC_APP_NAME. Not starting!
2024-06-06 15:03:34     at createAgent (/app/node_modules/.pnpm/newrelic@11.17.0/node_modules/newrelic/index.js:160:11)
2024-06-06 15:03:34     at initialize (/app/node_modules/.pnpm/newrelic@11.17.0/node_modules/newrelic/index.js:105:15)
2024-06-06 15:03:34     at Object.<anonymous> (/app/node_modules/.pnpm/newrelic@11.17.0/node_modules/newrelic/index.js:39:3)
2024-06-06 15:03:34     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2024-06-06 15:03:34     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2024-06-06 15:03:34     at Module.load (node:internal/modules/cjs/loader:1117:32)
2024-06-06 15:03:34     at Module._load (node:internal/modules/cjs/loader:958:12)
2024-06-06 15:03:34     at Module.require (node:internal/modules/cjs/loader:1141:19)
2024-06-06 15:03:34     at require (node:internal/modules/cjs/helpers:110:18)
2024-06-06 15:03:34     at 15477 (/app/packages/server/build/index.js:130385:18)

**Comment by abouolia** [comment]
It should work even without the newrelic variables. Let me check.

**Comment by calm108** [comment]
Well - it isn't crashing now BUT I cannot get SMTP to work (using resend) - should I file a new bug?

configured using these variables in .env:
# Mail
MAIL_HOST=smtp.resend.com
MAIL_USERNAME=resend
MAIL_PASSWORD=MYAPIKEY
MAIL_PORT=465
MAIL_SECURE=false
MAIL_FROM_NAME=Agencia
MAIL_FROM_ADDRESS=agencia@lifeonbtc.xyz

This is the error:



2024-06-06 16:07:11 Error: Unexpected socket close
2024-06-06 16:07:11     at Timeout._onTimeout (/app/node_modules/.pnpm/nodemailer@6.9.13/node_modules/nodemailer/lib/smtp-transport/index.js:190:31)
2024-06-06 16:07:11     at listOnTimeout (node:internal/timers:569:17)
2024-06-06 16:07:11     at process.processTimers (node:internal/timers:512:7)

**Comment by abouolia** [comment]
@calm108 Of course is not a bug, because I use Resend too, try to flip `MAIL_SECURE=true` because 465 port uses SSL/TLS.

**Comment by calm108** [comment]
Right - got it!  FYI set as true did not work set as TRUE did work.

**Comment by calm108** [comment]
All set - error was not cause of crashing - not sure what was but logs are clear now....

**Comment by abouolia** [comment]
@calm108 I will get rid of the Newrelic error once I get time, because it's so confusing. if you got anything else please let us know.
