### ISSUE TITLE
bigcapital server exits and throws error

### ISSUE THREAD

**Issue by jnduke300** [bigcapitalhq/bigcapital#507]
I have managed to follow all bigcapital docker installation process but failed to create account since bigcapital server exits once started.

One main error indicated on logs seems the server is missing NEW_RELIC_APP_NAME configuration on .env file. I have tried to set it but the issue is not sorted.

I know this NEW_RELIC_APP_NAME setting was once discussed and in one of the closed issues this seems to be closed. But this error keeps on popping up and cause all mess on the app.

I dont know the root cause of the error which makes the server to exit on runtime but whatever it is, this cause miscommunication between the user interface and Database layer. 

Bellow is the error I get 

bigcapital-server     | Node.js v18.16.0
bigcapital-server exited with code 1
bigcapital-server     | New Relic for Node.js was unable to bootstrap itself due to an error:
bigcapital-server     | Error: New Relic requires that you name this application!
bigcapital-server     | Set app_name in your newrelic.js or newrelic.cjs file or set environment variable
bigcapital-server     | NEW_RELIC_APP_NAME. Not starting!
bigcapital-server     |     at createAgent (/app/node_modules/.pnpm/newrelic@11.17.0/node_modules/newrelic/index.js:160:11)
bigcapital-server     |     at initialize (/app/node_modules/.pnpm/newrelic@11.17.0/node_modules/newrelic/index.js:105:15)
bigcapital-server     |     at Object.<anonymous> (/app/node_modules/.pnpm/newrelic@11.17.0/node_modules/newrelic/index.js:39:3)
bigcapital-server     |     at Module._compile (node:internal/modules/cjs/loader:1254:14)
bigcapital-server     |     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
bigcapital-server     |     at Module.load (node:internal/modules/cjs/loader:1117:32)
bigcapital-server     |     at Module._load (node:internal/modules/cjs/loader:958:12)
bigcapital-server     |     at Module.require (node:internal/modules/cjs/loader:1141:19)
bigcapital-server     |     at require (node:internal/modules/cjs/helpers:110:18)
bigcapital-server     |     at 15477 (/app/packages/server/build/index.js:130777:18)
bigcapital-server     | /app/node_modules/.pnpm/@smithy+config-resolver@3.0.0/node_modules/@smithy/config-resolver/dist-cjs/index.js:134
bigcapital-server     |     throw new Error("Region is missing");
bigcapital-server     |     ^
bigcapital-server     | 
bigcapital-server     | Error: Region is missing
bigcapital-server     |     at resolveRegionConfig (/app/node_modules/.pnpm/@smithy+config-resolver@3.0.0/node_modules/@smithy/config-resolver/dist-cjs/index.js:134:11)
bigcapital-server     |     at new S3Client (/app/node_modules/.pnpm/@aws-sdk+client-s3@3.583.0/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:8433:70)
bigcapital-server     |     at 82822 (/app/packages/server/build/index.js:24526:14)

**Comment by ArhumIshtiaq** [comment]
Any resolution to this?

**Comment by aeonoea** [comment]
Any of you were able to resolve this issue?

I have the same behaviour here, can't sign up and see this newrelic related error in the server logs.
