### ISSUE TITLE
Database always shows access denied no matter what the passwords are set in the Env

### ISSUE THREAD

**Issue by Dvalin21** [bigcapitalhq/bigcapital#702]
As the title says. Here is my log

```
2024-10-11 00:21:55+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.2.44+maria~bionic started.
2024-10-11 00:21:56+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2024-10-11 00:21:56+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.2.44+maria~bionic started.
2024-10-11 00:21:56+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
2024-10-11  0:21:56 139823765046976 [Note] mysqld (mysqld 10.2.44-MariaDB-1:10.2.44+maria~bionic) starting as process 1 ...
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: Uses event mutexes
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: Compressed tables use zlib 1.2.11
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: Using Linux native AIO
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: Number of pools: 1
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: Using SSE2 crc32 instructions
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: Completed initialization of buffer pool
2024-10-11  0:21:56 139823043397376 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: Highest supported file format is Barracuda.
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: 128 out of 128 rollback segments are active.
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: Creating shared tablespace for temporary tables
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2024-10-11  0:21:56 139823765046976 [Note] InnoDB: 5.7.38 started; log sequence number 2293829
2024-10-11  0:21:56 139822878398208 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2024-10-11  0:21:56 139823765046976 [Note] Plugin 'FEEDBACK' is disabled.
2024-10-11  0:21:56 139823765046976 [Note] Server socket created on IP: '0.0.0.0'.
2024-10-11  0:21:56 139823765046976 [Note] Reading of all Master_info entries succeeded
2024-10-11  0:21:56 139823765046976 [Note] Added new Master_info '' to hash table
2024-10-11  0:21:56 139823765046976 [Note] mysqld: ready for connections.
Version: '10.2.44-MariaDB-1:10.2.44+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2024-10-11  0:21:56 139822878398208 [Note] InnoDB: Buffer pool(s) load completed at 241011  0:21:56
2024-10-11  0:21:57 139823603558144 [Warning] Access denied for user 'bigcapital'@'172.21.0.7' (using password: YES)
2024-10-11  0:21:59 139823603558144 [Warning] Access denied for user 'bigcapital'@'172.21.0.8' (using password: YES)
```
Made sure that the passwords for root and the database was at least 8 to 12 characters, at least one capital, lowercase, digit, and special character. Still I get this error. Thanks in advance

**Comment by Dvalin21** [comment]
Logs from the server

```
Delete expired import files has started.
Error: connect ECONNREFUSED 172.21.0.3:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
    --------------------
    at Protocol._enqueue (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:116:18)
    at /app/node_modules/.pnpm/knex@3.1.0_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/dialects/mysql/index.js:71:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/app/node_modules/.pnpm/knex@3.1.0_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/dialects/mysql/index.js:66:12)
    at create (/app/node_modules/.pnpm/knex@3.1.0_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/client.js:262:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.21.0.3',
  port: 3306,
  fatal: true
}

```

**Comment by Sixth2538** [comment]
Similar issue here, are there you able to find a work around @Dvalin21?

**Comment by Dvalin21** [comment]
> Similar issue here, are there you able to find a work around [@Dvalin21](https://github.com/Dvalin21)?

I actually ended up switching to InvoiceNinja.  However, check Mongo and Mysql and see what versions are being used. I noticed in other projects I had to update closer to latest before getting passed this issue.
